---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fluentd
  namespace: logging
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fluentd
          resources:
            requests:
              cpu: 100m
