---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
spec:
  template:
    spec:
      containers:
        - name: fluent-bit
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
