---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 400m
