---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: letsencrypt-production-route53-key
    envs:
      - aws-route53.txt
    namespace: cert-manager
    type: Opaque