apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml"

# We patch the YAML from upstream to set the local-path storageClass the default one.
patches:
  - patch: |
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          "storageclass.kubernetes.io/is-default-class": "true"
