---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
  namespace: logging
spec:
  template:
    spec:
      containers:
      - name: cerebro
        resources:
          requests:
            cpu: 10m
