---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../vendor/katalog/dr/velero/velero-gcp
  - ../../vendor/katalog/dr/velero/velero-schedules
  - resources/velero-backup-storage-location.yml
  - resources/velero-volume-snapshot-location.yml

patchesStrategicMerge:
  - patches/velero.yml
  - patches/velero-service-account.yml
