apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-cluster-master
spec:
  template:
    spec:
      containers:
        - name: "opensearch"
          resources:
            limits:
              cpu: 2000m
              memory: 2G
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms1G -Xmx1G"
        - name: exporter
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 100Mi
