---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: infra
spec:
  errorOutputRef: errors
  fluentd:
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 50m
  fluentbit:
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 10m
        memory: 10Mi
  controlNamespace: logging