---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-cluster-master
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: opensearch
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
